version: '3'
services:

  db:
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--innodb-read-only-compressed=OFF"
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=Europe/Paris

  wordpress:
    build:
      args:
        user: wordpress
        uid: 1000
      context: ./wordpress
    working_dir: /var/www/html
    env_file: .env
    depends_on:
      - db
    volumes:
      #- wordpress:/var/www/html
      - type: bind
        source: wordpress/src
        target: /var/www/html
    ports:
      - 9000:9000

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/wordpress.template.conf:/etc/nginx/conf.d/default.template
      #- wordpress:/var/www/html:ro
      - type: bind
        source: wordpress/src
        target: /var/www/html
    restart: always
    depends_on:
      - db
      - wordpress
    command: /bin/bash -c "envsubst '$$DOMAIN' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - DOMAIN=${DOMAIN}

volumes:
  db_data:
    driver: local
